# Generated by Django 2.2 on 2019-04-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
